### ISSUE TITLE
Add container query for glyphs

### ISSUE THREAD

**Issue by Lenni009** [Lenni009/NMSWikiPageCreator#215]
This should only be done once Firefox supports `:has()` on all platforms ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility))

make this change:
```css
@media only screen and (max-width: 550px),
(1024px <=width <=1215px) {
	#portalglyphButtons {
		display: flex;
		flex-wrap: wrap;
	}
}
```
to this:
```css
@container (max-width: 470px) {
	#portalglyphButtons {
		display: flex;
		flex-wrap: wrap;
	}

        #portalglyphButtons button .glyph {
                margin-left: -.5em;
                margin-right: -.5em;
        }
}
```
